# Generated by Django 5.2.6 on 2025-09-14 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('actor1_name', models.CharField(max_length=120)),
                ('actor2_name', models.CharField(blank=True, max_length=120)),
                ('director_name', models.CharField(max_length=120)),
                ('movie_genre', models.CharField(choices=[('COMEDY', 'Comedy'), ('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCIFI', 'Sci-Fi'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)])),
            ],
        ),
    ]
