pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/NatalioH/videostore.git'
      }
    }

    stage('Sanity: show files') {
      steps {
        bat '''
        echo WORKSPACE: %cd%
        dir
        echo ----
        dir mymovie
        '''
      }
    }

    stage('Ensure Minikube up') {
      steps {
        bat '''
        REM If status fails, start the cluster (adjust driver if you use Hyper-V)
        "C:\\Program Files\\minikube\\minikube.exe" status || ^
        "C:\\Program Files\\minikube\\minikube.exe" start --driver=docker
        '''
      }
    }

    stage('Build image in Minikube') {
      steps {
        bat '''
        "C:\\Program Files\\minikube\\minikube.exe" image build -t mydjangoapp:latest mymovie
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        bat '''
        kubectl apply -f mymovie\\deployment.yaml
        kubectl apply -f mymovie\\service.yaml
        kubectl rollout status deployment/django-deployment
        kubectl get pods
        kubectl get svc
        '''
      }
    }
  }
}
